/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedAdvertiseRouteImport } from './routes/_authenticated/advertise'
import { Route as AuthenticatedAppealRouteImport } from './routes/_authenticated/appeal'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedCreatorProgramRouteImport } from './routes/_authenticated/creator-program'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMyBoostsRouteImport } from './routes/_authenticated/my-boosts'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatusRouteImport } from './routes/_authenticated/status'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as RUsernameRouteImport } from './routes/r.$username'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdEarningsRouteImport } from './routes/_authenticated/admin.ad-earnings'
import { Route as AuthenticatedAdminAdSettingsRouteImport } from './routes/_authenticated/admin.ad-settings'
import { Route as AuthenticatedAdminAppealsRouteImport } from './routes/_authenticated/admin.appeals'
import { Route as AuthenticatedAdminBoostsRouteImport } from './routes/_authenticated/admin.boosts'
import { Route as AuthenticatedAdminCopyrightRouteImport } from './routes/_authenticated/admin.copyright'
import { Route as AuthenticatedAdminEarningsRouteImport } from './routes/_authenticated/admin.earnings'
import { Route as AuthenticatedAdminManagementRouteImport } from './routes/_authenticated/admin.management'
import { Route as AuthenticatedAdminModerationLogRouteImport } from './routes/_authenticated/admin.moderation-log'
import { Route as AuthenticatedAdminPaymentSettingsRouteImport } from './routes/_authenticated/admin.payment-settings'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedBoostPostIdRouteImport } from './routes/_authenticated/boost.$postId'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatIdRouteImport } from './routes/_authenticated/chat.$id'
import { Route as AuthenticatedLiveIndexRouteImport } from './routes/_authenticated/live.index'
import { Route as AuthenticatedLiveIdRouteImport } from './routes/_authenticated/live.$id'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvertiseRoute = AuthenticatedAdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppealRoute = AuthenticatedAppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreatorProgramRoute =
  AuthenticatedCreatorProgramRouteImport.update({
    id: '/creator-program',
    path: '/creator-program',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyBoostsRoute = AuthenticatedMyBoostsRouteImport.update({
  id: '/my-boosts',
  path: '/my-boosts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatusRoute = AuthenticatedStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RUsernameRoute = RUsernameRouteImport.update({
  id: '/r/$username',
  path: '/r/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAdEarningsRoute =
  AuthenticatedAdminAdEarningsRouteImport.update({
    id: '/admin/ad-earnings',
    path: '/admin/ad-earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdSettingsRoute =
  AuthenticatedAdminAdSettingsRouteImport.update({
    id: '/admin/ad-settings',
    path: '/admin/ad-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAppealsRoute =
  AuthenticatedAdminAppealsRouteImport.update({
    id: '/admin/appeals',
    path: '/admin/appeals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBoostsRoute =
  AuthenticatedAdminBoostsRouteImport.update({
    id: '/admin/boosts',
    path: '/admin/boosts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCopyrightRoute =
  AuthenticatedAdminCopyrightRouteImport.update({
    id: '/admin/copyright',
    path: '/admin/copyright',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEarningsRoute =
  AuthenticatedAdminEarningsRouteImport.update({
    id: '/admin/earnings',
    path: '/admin/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminManagementRoute =
  AuthenticatedAdminManagementRouteImport.update({
    id: '/admin/management',
    path: '/admin/management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModerationLogRoute =
  AuthenticatedAdminModerationLogRouteImport.update({
    id: '/admin/moderation-log',
    path: '/admin/moderation-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentSettingsRoute =
  AuthenticatedAdminPaymentSettingsRouteImport.update({
    id: '/admin/payment-settings',
    path: '/admin/payment-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/admin/payouts',
    path: '/admin/payouts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoostPostIdRoute =
  AuthenticatedBoostPostIdRouteImport.update({
    id: '/boost/$postId',
    path: '/boost/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIdRoute = AuthenticatedChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveIndexRoute = AuthenticatedLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveIdRoute = AuthenticatedLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/advertise': typeof AuthenticatedAdvertiseRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/create': typeof AuthenticatedCreateRoute
  '/creator-program': typeof AuthenticatedCreatorProgramRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-boosts': typeof AuthenticatedMyBoostsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/support': typeof AuthenticatedSupportRoute
  '/r/$username': typeof RUsernameRoute
  '/admin/ad-earnings': typeof AuthenticatedAdminAdEarningsRoute
  '/admin/ad-settings': typeof AuthenticatedAdminAdSettingsRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/admin/copyright': typeof AuthenticatedAdminCopyrightRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/management': typeof AuthenticatedAdminManagementRoute
  '/admin/moderation-log': typeof AuthenticatedAdminModerationLogRoute
  '/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/boost/$postId': typeof AuthenticatedBoostPostIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/live/': typeof AuthenticatedLiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/advertise': typeof AuthenticatedAdvertiseRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/create': typeof AuthenticatedCreateRoute
  '/creator-program': typeof AuthenticatedCreatorProgramRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-boosts': typeof AuthenticatedMyBoostsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/status': typeof AuthenticatedStatusRoute
  '/support': typeof AuthenticatedSupportRoute
  '/r/$username': typeof RUsernameRoute
  '/admin/ad-earnings': typeof AuthenticatedAdminAdEarningsRoute
  '/admin/ad-settings': typeof AuthenticatedAdminAdSettingsRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/admin/copyright': typeof AuthenticatedAdminCopyrightRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/management': typeof AuthenticatedAdminManagementRoute
  '/admin/moderation-log': typeof AuthenticatedAdminModerationLogRoute
  '/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/boost/$postId': typeof AuthenticatedBoostPostIdRoute
  '/chat/$id': typeof AuthenticatedChatIdRoute
  '/live/$id': typeof AuthenticatedLiveIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/live': typeof AuthenticatedLiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/advertise': typeof AuthenticatedAdvertiseRoute
  '/_authenticated/appeal': typeof AuthenticatedAppealRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/creator-program': typeof AuthenticatedCreatorProgramRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/my-boosts': typeof AuthenticatedMyBoostsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/status': typeof AuthenticatedStatusRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/r/$username': typeof RUsernameRoute
  '/_authenticated/admin/ad-earnings': typeof AuthenticatedAdminAdEarningsRoute
  '/_authenticated/admin/ad-settings': typeof AuthenticatedAdminAdSettingsRoute
  '/_authenticated/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/_authenticated/admin/boosts': typeof AuthenticatedAdminBoostsRoute
  '/_authenticated/admin/copyright': typeof AuthenticatedAdminCopyrightRoute
  '/_authenticated/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/_authenticated/admin/management': typeof AuthenticatedAdminManagementRoute
  '/_authenticated/admin/moderation-log': typeof AuthenticatedAdminModerationLogRoute
  '/_authenticated/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/boost/$postId': typeof AuthenticatedBoostPostIdRoute
  '/_authenticated/chat/$id': typeof AuthenticatedChatIdRoute
  '/_authenticated/live/$id': typeof AuthenticatedLiveIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/live/': typeof AuthenticatedLiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/advertise'
    | '/appeal'
    | '/create'
    | '/creator-program'
    | '/home'
    | '/my-boosts'
    | '/notifications'
    | '/payment-methods'
    | '/profile'
    | '/reels'
    | '/search'
    | '/settings'
    | '/status'
    | '/support'
    | '/r/$username'
    | '/admin/ad-earnings'
    | '/admin/ad-settings'
    | '/admin/appeals'
    | '/admin/boosts'
    | '/admin/copyright'
    | '/admin/earnings'
    | '/admin/management'
    | '/admin/moderation-log'
    | '/admin/payment-settings'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/users'
    | '/boost/$postId'
    | '/chat/$id'
    | '/live/$id'
    | '/u/$username'
    | '/admin/'
    | '/chat/'
    | '/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/advertise'
    | '/appeal'
    | '/create'
    | '/creator-program'
    | '/home'
    | '/my-boosts'
    | '/notifications'
    | '/payment-methods'
    | '/profile'
    | '/reels'
    | '/search'
    | '/settings'
    | '/status'
    | '/support'
    | '/r/$username'
    | '/admin/ad-earnings'
    | '/admin/ad-settings'
    | '/admin/appeals'
    | '/admin/boosts'
    | '/admin/copyright'
    | '/admin/earnings'
    | '/admin/management'
    | '/admin/moderation-log'
    | '/admin/payment-settings'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/users'
    | '/boost/$postId'
    | '/chat/$id'
    | '/live/$id'
    | '/u/$username'
    | '/admin'
    | '/chat'
    | '/live'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/forgot-password'
    | '/reset-password'
    | '/welcome'
    | '/_authenticated/advertise'
    | '/_authenticated/appeal'
    | '/_authenticated/create'
    | '/_authenticated/creator-program'
    | '/_authenticated/home'
    | '/_authenticated/my-boosts'
    | '/_authenticated/notifications'
    | '/_authenticated/payment-methods'
    | '/_authenticated/profile'
    | '/_authenticated/reels'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/status'
    | '/_authenticated/support'
    | '/r/$username'
    | '/_authenticated/admin/ad-earnings'
    | '/_authenticated/admin/ad-settings'
    | '/_authenticated/admin/appeals'
    | '/_authenticated/admin/boosts'
    | '/_authenticated/admin/copyright'
    | '/_authenticated/admin/earnings'
    | '/_authenticated/admin/management'
    | '/_authenticated/admin/moderation-log'
    | '/_authenticated/admin/payment-settings'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/boost/$postId'
    | '/_authenticated/chat/$id'
    | '/_authenticated/live/$id'
    | '/_authenticated/u/$username'
    | '/_authenticated/admin/'
    | '/_authenticated/chat/'
    | '/_authenticated/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WelcomeRoute: typeof WelcomeRoute
  RUsernameRoute: typeof RUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advertise': {
      id: '/_authenticated/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AuthenticatedAdvertiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appeal': {
      id: '/_authenticated/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AuthenticatedAppealRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator-program': {
      id: '/_authenticated/creator-program'
      path: '/creator-program'
      fullPath: '/creator-program'
      preLoaderRoute: typeof AuthenticatedCreatorProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-boosts': {
      id: '/_authenticated/my-boosts'
      path: '/my-boosts'
      fullPath: '/my-boosts'
      preLoaderRoute: typeof AuthenticatedMyBoostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status': {
      id: '/_authenticated/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthenticatedStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/r/$username': {
      id: '/r/$username'
      path: '/r/$username'
      fullPath: '/r/$username'
      preLoaderRoute: typeof RUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ad-earnings': {
      id: '/_authenticated/admin/ad-earnings'
      path: '/admin/ad-earnings'
      fullPath: '/admin/ad-earnings'
      preLoaderRoute: typeof AuthenticatedAdminAdEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ad-settings': {
      id: '/_authenticated/admin/ad-settings'
      path: '/admin/ad-settings'
      fullPath: '/admin/ad-settings'
      preLoaderRoute: typeof AuthenticatedAdminAdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/appeals': {
      id: '/_authenticated/admin/appeals'
      path: '/admin/appeals'
      fullPath: '/admin/appeals'
      preLoaderRoute: typeof AuthenticatedAdminAppealsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/boosts': {
      id: '/_authenticated/admin/boosts'
      path: '/admin/boosts'
      fullPath: '/admin/boosts'
      preLoaderRoute: typeof AuthenticatedAdminBoostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/copyright': {
      id: '/_authenticated/admin/copyright'
      path: '/admin/copyright'
      fullPath: '/admin/copyright'
      preLoaderRoute: typeof AuthenticatedAdminCopyrightRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/earnings': {
      id: '/_authenticated/admin/earnings'
      path: '/admin/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AuthenticatedAdminEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/management': {
      id: '/_authenticated/admin/management'
      path: '/admin/management'
      fullPath: '/admin/management'
      preLoaderRoute: typeof AuthenticatedAdminManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation-log': {
      id: '/_authenticated/admin/moderation-log'
      path: '/admin/moderation-log'
      fullPath: '/admin/moderation-log'
      preLoaderRoute: typeof AuthenticatedAdminModerationLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payment-settings': {
      id: '/_authenticated/admin/payment-settings'
      path: '/admin/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AuthenticatedAdminPaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boost/$postId': {
      id: '/_authenticated/boost/$postId'
      path: '/boost/$postId'
      fullPath: '/boost/$postId'
      preLoaderRoute: typeof AuthenticatedBoostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$id': {
      id: '/_authenticated/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AuthenticatedChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/': {
      id: '/_authenticated/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof AuthenticatedLiveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live/$id': {
      id: '/_authenticated/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof AuthenticatedLiveIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdvertiseRoute: typeof AuthenticatedAdvertiseRoute
  AuthenticatedAppealRoute: typeof AuthenticatedAppealRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedCreatorProgramRoute: typeof AuthenticatedCreatorProgramRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMyBoostsRoute: typeof AuthenticatedMyBoostsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatusRoute: typeof AuthenticatedStatusRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminAdEarningsRoute: typeof AuthenticatedAdminAdEarningsRoute
  AuthenticatedAdminAdSettingsRoute: typeof AuthenticatedAdminAdSettingsRoute
  AuthenticatedAdminAppealsRoute: typeof AuthenticatedAdminAppealsRoute
  AuthenticatedAdminBoostsRoute: typeof AuthenticatedAdminBoostsRoute
  AuthenticatedAdminCopyrightRoute: typeof AuthenticatedAdminCopyrightRoute
  AuthenticatedAdminEarningsRoute: typeof AuthenticatedAdminEarningsRoute
  AuthenticatedAdminManagementRoute: typeof AuthenticatedAdminManagementRoute
  AuthenticatedAdminModerationLogRoute: typeof AuthenticatedAdminModerationLogRoute
  AuthenticatedAdminPaymentSettingsRoute: typeof AuthenticatedAdminPaymentSettingsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedBoostPostIdRoute: typeof AuthenticatedBoostPostIdRoute
  AuthenticatedChatIdRoute: typeof AuthenticatedChatIdRoute
  AuthenticatedLiveIdRoute: typeof AuthenticatedLiveIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedLiveIndexRoute: typeof AuthenticatedLiveIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdvertiseRoute: AuthenticatedAdvertiseRoute,
  AuthenticatedAppealRoute: AuthenticatedAppealRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedCreatorProgramRoute: AuthenticatedCreatorProgramRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMyBoostsRoute: AuthenticatedMyBoostsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatusRoute: AuthenticatedStatusRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminAdEarningsRoute: AuthenticatedAdminAdEarningsRoute,
  AuthenticatedAdminAdSettingsRoute: AuthenticatedAdminAdSettingsRoute,
  AuthenticatedAdminAppealsRoute: AuthenticatedAdminAppealsRoute,
  AuthenticatedAdminBoostsRoute: AuthenticatedAdminBoostsRoute,
  AuthenticatedAdminCopyrightRoute: AuthenticatedAdminCopyrightRoute,
  AuthenticatedAdminEarningsRoute: AuthenticatedAdminEarningsRoute,
  AuthenticatedAdminManagementRoute: AuthenticatedAdminManagementRoute,
  AuthenticatedAdminModerationLogRoute: AuthenticatedAdminModerationLogRoute,
  AuthenticatedAdminPaymentSettingsRoute:
    AuthenticatedAdminPaymentSettingsRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedBoostPostIdRoute: AuthenticatedBoostPostIdRoute,
  AuthenticatedChatIdRoute: AuthenticatedChatIdRoute,
  AuthenticatedLiveIdRoute: AuthenticatedLiveIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedLiveIndexRoute: AuthenticatedLiveIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WelcomeRoute: WelcomeRoute,
  RUsernameRoute: RUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
